name: 'fraude_credito'
version: '1.0'

profile: 'fraude_credito'

source-paths: ["models"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

# Conexión a BigQuery
outputs:
  dev:
    type: bigquery
    project: deteccion-fraude-transacciones
    dataset: fraude_credito
    threads: 1
    keyfile: "ruta/a/tu/archivo.json"
